services:
  db:
    image: postgres
    container_name: postgres-db
    env_file:
      - .envrc
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'",
        ]
      interval: 10s
      timeout: 1s
      retries: 5

  migrations:
    image: ghcr.io/kukymbr/goose-docker:3.22.1
    restart: no
    env_file:
      - .envrc
    depends_on:
      db:
        condition: service_healthy

    environment:
      - GOOSE_DRIVER =${GOOSE_DRIVER}
      - GOOSE_DBSTRING=${GOOSE_DBSTRING}
    volumes:
      - ./migrations:/migrations

  backend:
    build:
      dockerfile: Dockerfile.backend
    container_name: backend
    env_file:
      - .envrc
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db
