-- +goose Up
-- +goose StatementBegin
create extension if not exists citext;
create table Events(
    id bigint primary key generated by default as identity,
    name varchar(255) not null,
    description citext,
    location citext,
    start_time timestamp not null,
    end_time timestamp not null,
    participant_count int default 0,
    date_event date not null default(current_date),
    created_by bigint not null,
    foreign key(created_by) references Users(id) on delete cascade

);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
drop table Events;
-- +goose StatementEnd
