-- +goose Up
-- +goose StatementBegin
create extension if not exists citext;

create table Registrations(
    id bigint primary key generated by default as identity,
    event_id int not null,
    participant_id bigint not null,
    registration_date date not null,
    foreign key (event_id) references Events(id) on delete cascade,
    foreign key (participant_id) references Users(id) on delete cascade
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
drop table Registrations;
-- +goose StatementEnd
